// Auto-generated by build-gallery.js — do not edit manually
const GALLERY_PHOTOS = [
  {
    "original": "photos/0db78950-fcb7-43d6-ad53-88a025a851b5.JPG",
    "thumb": "photos/optimized/thumbs/0db78950-fcb7-43d6-ad53-88a025a851b5.webp",
    "lightbox": "photos/optimized/lightbox/0db78950-fcb7-43d6-ad53-88a025a851b5.webp"
  },
  {
    "original": "photos/0def93b4-6896-468d-9583-92b57c5eecb7.JPG",
    "thumb": "photos/optimized/thumbs/0def93b4-6896-468d-9583-92b57c5eecb7.webp",
    "lightbox": "photos/optimized/lightbox/0def93b4-6896-468d-9583-92b57c5eecb7.webp"
  },
  {
    "original": "photos/2a7db681-916d-4e4d-92d3-1ef1b2e7e4d0.JPG",
    "thumb": "photos/optimized/thumbs/2a7db681-916d-4e4d-92d3-1ef1b2e7e4d0.webp",
    "lightbox": "photos/optimized/lightbox/2a7db681-916d-4e4d-92d3-1ef1b2e7e4d0.webp"
  },
  {
    "original": "photos/2c252927-6294-46ec-9df4-f3db40b4bf9b.JPG",
    "thumb": "photos/optimized/thumbs/2c252927-6294-46ec-9df4-f3db40b4bf9b.webp",
    "lightbox": "photos/optimized/lightbox/2c252927-6294-46ec-9df4-f3db40b4bf9b.webp"
  },
  {
    "original": "photos/3B42346E-9E59-4B64-A5A0-4B9750DFED4C.JPG",
    "thumb": "photos/optimized/thumbs/3B42346E-9E59-4B64-A5A0-4B9750DFED4C.webp",
    "lightbox": "photos/optimized/lightbox/3B42346E-9E59-4B64-A5A0-4B9750DFED4C.webp"
  },
  {
    "original": "photos/3ff4f34b-4ab0-41e5-b19b-f85fd0f2e0c2.JPG",
    "thumb": "photos/optimized/thumbs/3ff4f34b-4ab0-41e5-b19b-f85fd0f2e0c2.webp",
    "lightbox": "photos/optimized/lightbox/3ff4f34b-4ab0-41e5-b19b-f85fd0f2e0c2.webp"
  },
  {
    "original": "photos/4c1e7e66-ee54-4f2c-8069-51af9d30a78d.JPG",
    "thumb": "photos/optimized/thumbs/4c1e7e66-ee54-4f2c-8069-51af9d30a78d.webp",
    "lightbox": "photos/optimized/lightbox/4c1e7e66-ee54-4f2c-8069-51af9d30a78d.webp"
  },
  {
    "original": "photos/4CE420B2-BE50-4DBF-8C87-792DF8DE0E67.JPG",
    "thumb": "photos/optimized/thumbs/4CE420B2-BE50-4DBF-8C87-792DF8DE0E67.webp",
    "lightbox": "photos/optimized/lightbox/4CE420B2-BE50-4DBF-8C87-792DF8DE0E67.webp"
  },
  {
    "original": "photos/5ec04d90-e438-498b-87c0-a326f76b5ee1.JPG",
    "thumb": "photos/optimized/thumbs/5ec04d90-e438-498b-87c0-a326f76b5ee1.webp",
    "lightbox": "photos/optimized/lightbox/5ec04d90-e438-498b-87c0-a326f76b5ee1.webp"
  },
  {
    "original": "photos/6B375A8E-58F0-40CF-91B4-6638510E24C4.JPG",
    "thumb": "photos/optimized/thumbs/6B375A8E-58F0-40CF-91B4-6638510E24C4.webp",
    "lightbox": "photos/optimized/lightbox/6B375A8E-58F0-40CF-91B4-6638510E24C4.webp"
  },
  {
    "original": "photos/7f08ba51-0174-4cda-987c-323be30aa448.JPG",
    "thumb": "photos/optimized/thumbs/7f08ba51-0174-4cda-987c-323be30aa448.webp",
    "lightbox": "photos/optimized/lightbox/7f08ba51-0174-4cda-987c-323be30aa448.webp"
  },
  {
    "original": "photos/8ba3d447-c33b-403d-b228-b02accdab564.JPG",
    "thumb": "photos/optimized/thumbs/8ba3d447-c33b-403d-b228-b02accdab564.webp",
    "lightbox": "photos/optimized/lightbox/8ba3d447-c33b-403d-b228-b02accdab564.webp"
  },
  {
    "original": "photos/8eddf303-73fb-4789-a5ac-388869807105.JPG",
    "thumb": "photos/optimized/thumbs/8eddf303-73fb-4789-a5ac-388869807105.webp",
    "lightbox": "photos/optimized/lightbox/8eddf303-73fb-4789-a5ac-388869807105.webp"
  },
  {
    "original": "photos/14b6e0e6-51cf-4797-b90c-6feaa632a2ed.JPG",
    "thumb": "photos/optimized/thumbs/14b6e0e6-51cf-4797-b90c-6feaa632a2ed.webp",
    "lightbox": "photos/optimized/lightbox/14b6e0e6-51cf-4797-b90c-6feaa632a2ed.webp"
  },
  {
    "original": "photos/29CCBD97-F0DE-48CA-BD16-F5A6110F547A.JPG",
    "thumb": "photos/optimized/thumbs/29CCBD97-F0DE-48CA-BD16-F5A6110F547A.webp",
    "lightbox": "photos/optimized/lightbox/29CCBD97-F0DE-48CA-BD16-F5A6110F547A.webp"
  },
  {
    "original": "photos/38b317c3-2010-4e0e-a44b-0abcc099feaa.JPG",
    "thumb": "photos/optimized/thumbs/38b317c3-2010-4e0e-a44b-0abcc099feaa.webp",
    "lightbox": "photos/optimized/lightbox/38b317c3-2010-4e0e-a44b-0abcc099feaa.webp"
  },
  {
    "original": "photos/61dc8aed-3613-4183-99f5-c8eb3aae6cf9.JPG",
    "thumb": "photos/optimized/thumbs/61dc8aed-3613-4183-99f5-c8eb3aae6cf9.webp",
    "lightbox": "photos/optimized/lightbox/61dc8aed-3613-4183-99f5-c8eb3aae6cf9.webp"
  },
  {
    "original": "photos/73ac68bb-9a46-4973-817e-8ea4800600e2.JPG",
    "thumb": "photos/optimized/thumbs/73ac68bb-9a46-4973-817e-8ea4800600e2.webp",
    "lightbox": "photos/optimized/lightbox/73ac68bb-9a46-4973-817e-8ea4800600e2.webp"
  },
  {
    "original": "photos/79ab6117-aa0a-4ccf-a7b6-f983a87022b4.JPG",
    "thumb": "photos/optimized/thumbs/79ab6117-aa0a-4ccf-a7b6-f983a87022b4.webp",
    "lightbox": "photos/optimized/lightbox/79ab6117-aa0a-4ccf-a7b6-f983a87022b4.webp"
  },
  {
    "original": "photos/86ceb7c8-0774-41df-a9a9-76771b4fea21.JPG",
    "thumb": "photos/optimized/thumbs/86ceb7c8-0774-41df-a9a9-76771b4fea21.webp",
    "lightbox": "photos/optimized/lightbox/86ceb7c8-0774-41df-a9a9-76771b4fea21.webp"
  },
  {
    "original": "photos/91ac4d50-fb6b-4f43-8c1b-457e68bad9ac.jpg",
    "thumb": "photos/optimized/thumbs/91ac4d50-fb6b-4f43-8c1b-457e68bad9ac.webp",
    "lightbox": "photos/optimized/lightbox/91ac4d50-fb6b-4f43-8c1b-457e68bad9ac.webp"
  },
  {
    "original": "photos/140c173d-b245-45d4-a02c-5294a5ca757c.JPG",
    "thumb": "photos/optimized/thumbs/140c173d-b245-45d4-a02c-5294a5ca757c.webp",
    "lightbox": "photos/optimized/lightbox/140c173d-b245-45d4-a02c-5294a5ca757c.webp"
  },
  {
    "original": "photos/605b6ecc-e485-404f-81f2-09743414713d.JPG",
    "thumb": "photos/optimized/thumbs/605b6ecc-e485-404f-81f2-09743414713d.webp",
    "lightbox": "photos/optimized/lightbox/605b6ecc-e485-404f-81f2-09743414713d.webp"
  },
  {
    "original": "photos/656ec2e6-5866-4786-83b9-7364bf19fb15.JPG",
    "thumb": "photos/optimized/thumbs/656ec2e6-5866-4786-83b9-7364bf19fb15.webp",
    "lightbox": "photos/optimized/lightbox/656ec2e6-5866-4786-83b9-7364bf19fb15.webp"
  },
  {
    "original": "photos/721fbdc6-7776-43d2-a81b-9892dfe2b081.JPG",
    "thumb": "photos/optimized/thumbs/721fbdc6-7776-43d2-a81b-9892dfe2b081.webp",
    "lightbox": "photos/optimized/lightbox/721fbdc6-7776-43d2-a81b-9892dfe2b081.webp"
  },
  {
    "original": "photos/810a951d-1c25-4ba6-84b5-a24f35b55148.JPG",
    "thumb": "photos/optimized/thumbs/810a951d-1c25-4ba6-84b5-a24f35b55148.webp",
    "lightbox": "photos/optimized/lightbox/810a951d-1c25-4ba6-84b5-a24f35b55148.webp"
  },
  {
    "original": "photos/5859db84-9bb7-49c2-bedc-85c16eee1fc6.JPG",
    "thumb": "photos/optimized/thumbs/5859db84-9bb7-49c2-bedc-85c16eee1fc6.webp",
    "lightbox": "photos/optimized/lightbox/5859db84-9bb7-49c2-bedc-85c16eee1fc6.webp"
  },
  {
    "original": "photos/9482d5db-8140-4540-80b9-ab33318be414.jpg",
    "thumb": "photos/optimized/thumbs/9482d5db-8140-4540-80b9-ab33318be414.webp",
    "lightbox": "photos/optimized/lightbox/9482d5db-8140-4540-80b9-ab33318be414.webp"
  },
  {
    "original": "photos/86116c4a-00b7-4ee3-8bc4-cc4f9a4b7bb8.JPG",
    "thumb": "photos/optimized/thumbs/86116c4a-00b7-4ee3-8bc4-cc4f9a4b7bb8.webp",
    "lightbox": "photos/optimized/lightbox/86116c4a-00b7-4ee3-8bc4-cc4f9a4b7bb8.webp"
  },
  {
    "original": "photos/456698e9-e03f-41fc-af5b-5946d9a9f2a3.jpg",
    "thumb": "photos/optimized/thumbs/456698e9-e03f-41fc-af5b-5946d9a9f2a3.webp",
    "lightbox": "photos/optimized/lightbox/456698e9-e03f-41fc-af5b-5946d9a9f2a3.webp"
  },
  {
    "original": "photos/33809429-126b-438e-8a7e-8e7bbec02775.JPG",
    "thumb": "photos/optimized/thumbs/33809429-126b-438e-8a7e-8e7bbec02775.webp",
    "lightbox": "photos/optimized/lightbox/33809429-126b-438e-8a7e-8e7bbec02775.webp"
  },
  {
    "original": "photos/66352672-F0C1-417F-A54B-D859569144F7.JPG",
    "thumb": "photos/optimized/thumbs/66352672-F0C1-417F-A54B-D859569144F7.webp",
    "lightbox": "photos/optimized/lightbox/66352672-F0C1-417F-A54B-D859569144F7.webp"
  },
  {
    "original": "photos/a1a0187e-3a85-42b7-b282-687f91587d88.JPG",
    "thumb": "photos/optimized/thumbs/a1a0187e-3a85-42b7-b282-687f91587d88.webp",
    "lightbox": "photos/optimized/lightbox/a1a0187e-3a85-42b7-b282-687f91587d88.webp"
  },
  {
    "original": "photos/ac23a558-ae6a-4842-8c9a-224892777743.JPG",
    "thumb": "photos/optimized/thumbs/ac23a558-ae6a-4842-8c9a-224892777743.webp",
    "lightbox": "photos/optimized/lightbox/ac23a558-ae6a-4842-8c9a-224892777743.webp"
  },
  {
    "original": "photos/aeddbce1-6e11-4e4b-b7b4-27bad1b84529.JPG",
    "thumb": "photos/optimized/thumbs/aeddbce1-6e11-4e4b-b7b4-27bad1b84529.webp",
    "lightbox": "photos/optimized/lightbox/aeddbce1-6e11-4e4b-b7b4-27bad1b84529.webp"
  },
  {
    "original": "photos/b298e163-f952-41fd-9403-d18b03a405b8.JPG",
    "thumb": "photos/optimized/thumbs/b298e163-f952-41fd-9403-d18b03a405b8.webp",
    "lightbox": "photos/optimized/lightbox/b298e163-f952-41fd-9403-d18b03a405b8.webp"
  },
  {
    "original": "photos/b0997bd1-9197-4e2d-81f1-55c33dd38f2d.JPG",
    "thumb": "photos/optimized/thumbs/b0997bd1-9197-4e2d-81f1-55c33dd38f2d.webp",
    "lightbox": "photos/optimized/lightbox/b0997bd1-9197-4e2d-81f1-55c33dd38f2d.webp"
  },
  {
    "original": "photos/b5287ab3-c30d-41a0-9372-404bc3e578c9.JPG",
    "thumb": "photos/optimized/thumbs/b5287ab3-c30d-41a0-9372-404bc3e578c9.webp",
    "lightbox": "photos/optimized/lightbox/b5287ab3-c30d-41a0-9372-404bc3e578c9.webp"
  },
  {
    "original": "photos/cffb7ec9-e9ff-4deb-8726-65cf028e1082.JPG",
    "thumb": "photos/optimized/thumbs/cffb7ec9-e9ff-4deb-8726-65cf028e1082.webp",
    "lightbox": "photos/optimized/lightbox/cffb7ec9-e9ff-4deb-8726-65cf028e1082.webp"
  },
  {
    "original": "photos/d944f872-5588-44b6-9646-59d50676c89f.JPG",
    "thumb": "photos/optimized/thumbs/d944f872-5588-44b6-9646-59d50676c89f.webp",
    "lightbox": "photos/optimized/lightbox/d944f872-5588-44b6-9646-59d50676c89f.webp"
  },
  {
    "original": "photos/d69871b1-ea67-49c7-bafe-12d6caf0fcf1.JPG",
    "thumb": "photos/optimized/thumbs/d69871b1-ea67-49c7-bafe-12d6caf0fcf1.webp",
    "lightbox": "photos/optimized/lightbox/d69871b1-ea67-49c7-bafe-12d6caf0fcf1.webp"
  },
  {
    "original": "photos/e835fafe-8810-4b78-a8f9-34048320546b.JPG",
    "thumb": "photos/optimized/thumbs/e835fafe-8810-4b78-a8f9-34048320546b.webp",
    "lightbox": "photos/optimized/lightbox/e835fafe-8810-4b78-a8f9-34048320546b.webp"
  },
  {
    "original": "photos/EE2B722D-0BF2-4C87-8406-8A97E0EFDC73.JPG",
    "thumb": "photos/optimized/thumbs/EE2B722D-0BF2-4C87-8406-8A97E0EFDC73.webp",
    "lightbox": "photos/optimized/lightbox/EE2B722D-0BF2-4C87-8406-8A97E0EFDC73.webp"
  },
  {
    "original": "photos/ef218cd9-cce3-4798-b670-8aecc85a408c.JPG",
    "thumb": "photos/optimized/thumbs/ef218cd9-cce3-4798-b670-8aecc85a408c.webp",
    "lightbox": "photos/optimized/lightbox/ef218cd9-cce3-4798-b670-8aecc85a408c.webp"
  },
  {
    "original": "photos/f6ba765e-71fb-4861-bc4f-ac4347e62ff0.JPG",
    "thumb": "photos/optimized/thumbs/f6ba765e-71fb-4861-bc4f-ac4347e62ff0.webp",
    "lightbox": "photos/optimized/lightbox/f6ba765e-71fb-4861-bc4f-ac4347e62ff0.webp"
  },
  {
    "original": "photos/f663ab27-cf70-4076-906a-3d846182f999.JPG",
    "thumb": "photos/optimized/thumbs/f663ab27-cf70-4076-906a-3d846182f999.webp",
    "lightbox": "photos/optimized/lightbox/f663ab27-cf70-4076-906a-3d846182f999.webp"
  },
  {
    "original": "photos/f1264776-0a8d-4608-a7a3-cb39024953d1.JPG",
    "thumb": "photos/optimized/thumbs/f1264776-0a8d-4608-a7a3-cb39024953d1.webp",
    "lightbox": "photos/optimized/lightbox/f1264776-0a8d-4608-a7a3-cb39024953d1.webp"
  },
  {
    "original": "photos/fca9d859-8373-44bb-bcb5-183277e5d33b.JPG",
    "thumb": "photos/optimized/thumbs/fca9d859-8373-44bb-bcb5-183277e5d33b.webp",
    "lightbox": "photos/optimized/lightbox/fca9d859-8373-44bb-bcb5-183277e5d33b.webp"
  },
  {
    "original": "photos/IMG_0007.jpg",
    "thumb": "photos/optimized/thumbs/IMG_0007.webp",
    "lightbox": "photos/optimized/lightbox/IMG_0007.webp"
  },
  {
    "original": "photos/IMG_0995.jpg",
    "thumb": "photos/optimized/thumbs/IMG_0995.webp",
    "lightbox": "photos/optimized/lightbox/IMG_0995.webp"
  },
  {
    "original": "photos/IMG_1237.jpg",
    "thumb": "photos/optimized/thumbs/IMG_1237.webp",
    "lightbox": "photos/optimized/lightbox/IMG_1237.webp"
  },
  {
    "original": "photos/IMG_2326.jpg",
    "thumb": "photos/optimized/thumbs/IMG_2326.webp",
    "lightbox": "photos/optimized/lightbox/IMG_2326.webp"
  },
  {
    "original": "photos/IMG_2329.jpg",
    "thumb": "photos/optimized/thumbs/IMG_2329.webp",
    "lightbox": "photos/optimized/lightbox/IMG_2329.webp"
  },
  {
    "original": "photos/IMG_2339.jpg",
    "thumb": "photos/optimized/thumbs/IMG_2339.webp",
    "lightbox": "photos/optimized/lightbox/IMG_2339.webp"
  },
  {
    "original": "photos/IMG_2346.jpg",
    "thumb": "photos/optimized/thumbs/IMG_2346.webp",
    "lightbox": "photos/optimized/lightbox/IMG_2346.webp"
  },
  {
    "original": "photos/IMG_2905.jpg",
    "thumb": "photos/optimized/thumbs/IMG_2905.webp",
    "lightbox": "photos/optimized/lightbox/IMG_2905.webp"
  },
  {
    "original": "photos/IMG_3162.jpg",
    "thumb": "photos/optimized/thumbs/IMG_3162.webp",
    "lightbox": "photos/optimized/lightbox/IMG_3162.webp"
  },
  {
    "original": "photos/IMG_3300.JPG",
    "thumb": "photos/optimized/thumbs/IMG_3300.webp",
    "lightbox": "photos/optimized/lightbox/IMG_3300.webp"
  },
  {
    "original": "photos/IMG_3372.jpg",
    "thumb": "photos/optimized/thumbs/IMG_3372.webp",
    "lightbox": "photos/optimized/lightbox/IMG_3372.webp"
  },
  {
    "original": "photos/IMG_3734.jpg",
    "thumb": "photos/optimized/thumbs/IMG_3734.webp",
    "lightbox": "photos/optimized/lightbox/IMG_3734.webp"
  },
  {
    "original": "photos/IMG_3779.jpg",
    "thumb": "photos/optimized/thumbs/IMG_3779.webp",
    "lightbox": "photos/optimized/lightbox/IMG_3779.webp"
  },
  {
    "original": "photos/IMG_5740.JPG",
    "thumb": "photos/optimized/thumbs/IMG_5740.webp",
    "lightbox": "photos/optimized/lightbox/IMG_5740.webp"
  },
  {
    "original": "photos/IMG_5741.JPG",
    "thumb": "photos/optimized/thumbs/IMG_5741.webp",
    "lightbox": "photos/optimized/lightbox/IMG_5741.webp"
  },
  {
    "original": "photos/IMG_6040.jpg",
    "thumb": "photos/optimized/thumbs/IMG_6040.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6040.webp"
  },
  {
    "original": "photos/IMG_6072.jpg",
    "thumb": "photos/optimized/thumbs/IMG_6072.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6072.webp"
  },
  {
    "original": "photos/IMG_6465.jpg",
    "thumb": "photos/optimized/thumbs/IMG_6465.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6465.webp"
  },
  {
    "original": "photos/IMG_6660.jpg",
    "thumb": "photos/optimized/thumbs/IMG_6660.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6660.webp"
  },
  {
    "original": "photos/IMG_6873.jpg",
    "thumb": "photos/optimized/thumbs/IMG_6873.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6873.webp"
  },
  {
    "original": "photos/IMG_6950.JPG",
    "thumb": "photos/optimized/thumbs/IMG_6950.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6950.webp"
  },
  {
    "original": "photos/IMG_6951.JPG",
    "thumb": "photos/optimized/thumbs/IMG_6951.webp",
    "lightbox": "photos/optimized/lightbox/IMG_6951.webp"
  },
  {
    "original": "photos/IMG_7155.jpg",
    "thumb": "photos/optimized/thumbs/IMG_7155.webp",
    "lightbox": "photos/optimized/lightbox/IMG_7155.webp"
  },
  {
    "original": "photos/IMG_7157.jpg",
    "thumb": "photos/optimized/thumbs/IMG_7157.webp",
    "lightbox": "photos/optimized/lightbox/IMG_7157.webp"
  },
  {
    "original": "photos/IMG_7980.JPG",
    "thumb": "photos/optimized/thumbs/IMG_7980.webp",
    "lightbox": "photos/optimized/lightbox/IMG_7980.webp"
  },
  {
    "original": "photos/IMG_7981.JPG",
    "thumb": "photos/optimized/thumbs/IMG_7981.webp",
    "lightbox": "photos/optimized/lightbox/IMG_7981.webp"
  },
  {
    "original": "photos/IMG_8883.jpg",
    "thumb": "photos/optimized/thumbs/IMG_8883.webp",
    "lightbox": "photos/optimized/lightbox/IMG_8883.webp"
  },
  {
    "original": "photos/IMG_9417.jpg",
    "thumb": "photos/optimized/thumbs/IMG_9417.webp",
    "lightbox": "photos/optimized/lightbox/IMG_9417.webp"
  },
  {
    "original": "photos/IMG_9533.jpg",
    "thumb": "photos/optimized/thumbs/IMG_9533.webp",
    "lightbox": "photos/optimized/lightbox/IMG_9533.webp"
  },
  {
    "original": "photos/IMG_9548.jpg",
    "thumb": "photos/optimized/thumbs/IMG_9548.webp",
    "lightbox": "photos/optimized/lightbox/IMG_9548.webp"
  }
];
