/**
 * Scan the photos/ folder and generate js/gallery-data.js
 * Run: node build-gallery.js
 */
const fs = require('fs');
const path = require('path');

const PHOTOS_DIR = path.join(__dirname, 'photos');
const OUTPUT = path.join(__dirname, 'js', 'gallery-data.js');
const IMAGE_EXT = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.avif', '.bmp', '.svg'];

const files = fs.readdirSync(PHOTOS_DIR)
    .filter(f => {
        const ext = path.extname(f).toLowerCase();
        return IMAGE_EXT.includes(ext) && !f.startsWith('.');
    })
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

const photos = files.map((file) => {
    const baseName = path.parse(file).name;
    return {
        original: `photos/${file}`,
        thumb: `photos/optimized/thumbs/${baseName}.webp`,
        lightbox: `photos/optimized/lightbox/${baseName}.webp`
    };
});

const jsContent = `// Auto-generated by build-gallery.js — do not edit manually\nconst GALLERY_PHOTOS = ${JSON.stringify(photos, null, 2)};\n`;

fs.writeFileSync(OUTPUT, jsContent);
console.log(`✅ gallery-data.js generato con ${files.length} immagini`);
